/* Importing listener functions  */
//import * from

/* document.getElementById("firstPickNum").innerHTML = "42";*/
/* Declaration of picked numbers input value  */

/*  - - pick numbers  -    */



//import { multiplyQuad } from "extracode.js";



//console.log(multiplyQuad())





console.log("--Enter Picks first ,--- then click submit------------space-- ");






/* Button event listeners   */

const initListen = function (ev) {
  document.getElementById("retryButton").addEventListener(`click`, reset);
  document.getElementById("submitButton").addEventListener(`click`, send);
};

const reset = function (ev) {
  ev.preventDefault();


  document.getElementById("form-picks").reset();

  document.getElementById("defaultCheckboxImage").innerHTML=( "<img  name='defaultImage' class='checkMarkVanilla' src='images/checkmarkvanilla.png' alt='default checkmark'> " )



};



let pickOne = document.getElementById("firstPickNum").value;
let pickTwo = document.getElementById("secondPickNum").value;
let pickThree = document.getElementById("thirdPickNum").value;



let picks =[pickOne, pickTwo, pickThree];
JSON.stringify(picks)


const send = function (ev) {
  ev.preventDefault();


  document.getElementById("firstPickLabel").innerHTML=("Your first pick is " + pickOne );
  document.getElementById("secondPickLabel").innerHTML=("Your second pick is " + pickTwo );
  document.getElementById("thirdPickLabel").innerHTML=("Your third pick is " + pickThree );
  
  
  //alert ("Your first pick is " + pickOne + ", Your second pick is " + pickTwo + ", Your third pick is " + pickThree + "." +  " Are you sure you want to continue? "  );


  pickOne = document.getElementById("firstPickNum").value;
  pickThree = document.getElementById("thirdPickNum").value;
  pickTwo = document.getElementById("secondPickNum").value;


   let picks =[pickOne, pickTwo, pickThree];
  JSON.stringify(picks)
  console.log(picks + " here") ; 

////////////////////////////////
//////////////////////////////////////////
  /* Random Winning number generator model! */ 
/*
function randomWinningNumbers(){  

let winningNumOne = Math.floor(Math.random() * 100 );
let winningNumTwo = Math.floor(Math.random() * 100 );
let winningNumThree = Math.floor(Math.random() * 100 );

console.log("First Random pick")
console.log(winningNumOne);
console.log("Second Random pick")
console.log(winningNumTwo);
console.log("Third Random pick")
console.log(winningNumThree);
} ; 
randomWinningNumbers();

console.log("running random winning numbers")
*/ 
/*  -----------------------*/
  /* SEND block continue     */ 
  ////////////////////////////
  ////////////////////////
  /////////////////

let winningNumOne = 5; 
let winningNumTwo = 10; 
let winningNumThree = 15; 

let winningNumbers = []; 
winningNumbers = [winningNumOne, winningNumTwo, winningNumThree];

JSON.stringify(winningNumbers)


console.log("The winning numbers are")
console.log(winningNumbers);
console.log("Your pick 3 Numbers are  ")
console.log(picks)




/* WIN / LOSE - console.log logic */
       /*truthy is a win function , 
        whereas falsey is a lose.   */
if (winningNumbers[0] == picks[0] && winningNumbers[1] == picks[1] && winningNumbers[2] == picks[2] ) 
{
    console.log(" WINNER!!!! ")
     
    /* green checkmark logo */
    let greenCheck = "'<img src= images/checkmarkgreen.png class='checkMarkVanilla'  '>'"
    document.getElementById("defaultCheckboxImage").innerHTML= greenCheck




        /* Losing function generated by falsey */  //   //     
}else{  
    console.log(" This match lost ")
    let greenCheck = "'<img src= images/checkmarkred.png class='checkMarkVanilla'  '>'"
    document.getElementById("defaultCheckboxImage").innerHTML= greenCheck
  }
    
/////////////////////  


console.log(" -------" + picks + "------" )


function picksforJson(){
  JSON.stringify(picks)
  console.log("the function calls the picks" + picks )

} 
return picksforJson(); 

};
//export {picks}

console.log(picks)

document.addEventListener(`DOMContentLoaded`, initListen);










/* Logging out / checking of pick numbers */

/*

















/*    sample random stuff    
console.log("---space ------------space -- ");


let w1 = 5;

let winOne = document.getElementById("firstPickWin").value;
let winTwo = document.getElementById("secondPickWin").value;
let winThree = document.getElementById("thirdPickWin").value;

winOne = parseInt(winOne);
winTwo = parseInt(winTwo);
winThree = parseInt(winThree);

let winArray = [winOne, winTwo, winThree];

console.log(winArray);
console.log(winOne);
console.log(winTwo);
console.log(winThree);



let picks =[]
let pickNumbersObject = {
  pickOne: document.getElementById("firstPickNum").value,
  
  pickThree: document.getElementById("thirdPickNum").value,
  pickTwo: document.getElementById("secondPickNum").value,
}
parseInt(picks);
picks.push(pickNumbersObject);
console.log(picks);

winOne = picks[0];
winTwo = picks[1];
winThree = picks [2];

console.log(picks)


 Sample stuff */ 


/* old code function   */ 

/*function winOrLose() {
  if (pickArray[0] == winArray[0] && pickArray[1] == winArray[1] && pickArray[2] == winArray[2]) {
    console.log("WINNER!!!");
    let winOne = 4;
    console.log(winArray);
  } else {
    console.log("Try again next time !");
  }
}

winOrLose();/  *
















/* 
let pickOne = document.getElementById("firstPickNum").value;
let pickTwo = document.getElementById("secondPickNum").value;
let pickThree = document.getElementById("thirdPickNum").value;


pickOne = parseInt(pickOne);
pickTwo = parseInt(pickTwo);
pickThree = parseInt(pickThree);

const pickArray = [pickOne, pickTwo, pickThree];

console.log(pickOne);
console.log(pickTwo);
console.log(pickThree);
console.log(pickArray);


/*  */



/*   Bunch of extra display JavaScript i was practicing.     

import multiplyTrio from "./extracode.js"

console.log(multiplyTrio(20,40,200))

const pickArray = [pickOne, pickTwo, pickThree];

console.log(pickOne);
console.log(pickTwo);
console.log(pickThree);
console.log(pickArray);

let list = [56 , 42 , 91 ,"HUT HUT HIKE"]

list.pop();

console.log(list.length)

/* the .pop() removes the last entry  


list.push("playfootball")

/*  the .push() method adds another item at the 
    end of an array  

console.log(list.length)

/* the .list method , gives us the entire length of the array . 
which has increased by one   


console.log(list[3])
console.log(list[0])


/*  /

list.unshift("start a football game")

console.log(list)

/* Arrays modification can be done  by 
 referencing the indexed number.   /

list[4] =  "winafootballgame"
console.log(list[3])



console.log(list)





const x = [{
name:"Vampeyer",
age :31,
education:"I.T./Web-Dev",
location:"Louisville, Ky",
powerLevel :9583,
radiationLevel:76,
}]


console.log(x[0])

console.log("This is a demo of the authors details" 
 + "both inside an object " + "inside in array" )  
console.log(typeof x)  



console.log(x[0])

 
function isString(value){
    return typeof value == "string";  
  }
 

 
  */
